function [fitresult, gof] = fitGauss(xf, xA,low,up)
%CREATEFIT(XF,XA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xf
%      Y Output: xA
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
%  Auto-generated by MATLAB on 04-Apr-2022 11:37:53
%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xf, xA );
% Set up fittype and options.
ft = fittype( 'a*exp(-(x-b)^2/c)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = low;
opts.Upper = up;
opts.StartPoint = (low+up)./2;
opts.Robust = 'LAR';
[fitresult, gof] = fit( xData, yData, ft, opts );% Fit model to data.


